### ISSUE TITLE
DRG Todo (Endwalker Edition)

### ISSUE THREAD

**Issue by ebshimizu** [xivanalysis/xivanalysis#1278]
First part of the list addressed in PR #1277
This list supersedes #962 

Remaining issues

- [ ] All modules that currently use BuffWindow (Lance Charge, Dragon Sight) are waiting for Core BuffWindow to be merged. Battle Litany module will also be evaluated for compatibility with BuffWindow at that time.
- [ ] Blood of the Dragon module Analyser port is waiting for a combos event (i think that's in #1272)
- [ ] Tinctures and Combos will be updated when the corresponding core modules get updated
- [ ] Buffs module needs to be ported to Analyser
- [ ] Positionals module is scheduled for deletion when EW releases (lmao bye)

Expected EW changes
- [ ] Blood of the Dragon no longer needs to track gauge
- [ ] Usage for Wyrmwind Thrust (probably checklist)
- [ ] Life surge consumers will be chaotic spring and heaven's thrust
- [ ] SSD and LS have two charges
