### ISSUE TITLE
BLM Endwalker Todo list

### ISSUE THREAD

**Issue by AkairyuGestalter** [xivanalysis/xivanalysis#1290]
Non-exhaustive list of things that BLM will need for Endwalker support:
- [x] Actions entries for new spells
- [x] Remove action/status entries for Eno chan
- [x] Update Manafont Cooldown
- [x] Add charges to Sharpcast
- [x] Add AoEUsages entries for High Fire/Blizzard II
- [x] Update Gauge to handle Fire/Ice state changes from High Fire/Blizzard II
- [x] Update Gauge to handle Paradox gain/usage (incl refreshing AF/UI timer)
- [x] Update Gauge to handle gaining Polyglot from Amplifier
- [x] Ding for overcapping Paradox
- [x] Review post-launch theorycrafting & update RotationWatchdog as needed
- [ ] Fix Thunder clip tracking since Thundercloud so long now
