### ISSUE TITLE
DNC Endwalker Todo list

### ISSUE THREAD

**Issue by AkairyuGestalter** [xivanalysis/xivanalysis#1291]
Non-exhaustive list of things DNC will need for Endwalker support:
- [x] Actions entries for new abilities
- [x] Statuses entries/pruning for update proc structure
- [x] Update Procs to handle update proc structure
- [x] Update AoEUsages to ding for ST hits on AoE procs
- [x] Update Gauge to handle now-deterministic self-generation of Esprit
- [x] Remove Improvisation from Esprit Gauge generation
- [ ] Change Devilment-on-time check to require it as the first action under Technical Finish
- [ ] (Pending confirmation) Add Tillana-on-time check to require it before Standard Step under Technical Finish

**Comment by AkairyuGestalter** [comment]
DNC todos for initial support complete, Tillana timing checks and other suggestions are still being worked out pending balance changes when Savage launches. Closing.
