### ISSUE TITLE
WHM Analyser Todo List

### ISSUE THREAD

**Issue by AzariahAeroborn** [xivanalysis/xivanalysis#1302]
- [ ] Convert DoTs to core DoTs
- [ ] Convert Lilies to core Gauge (Counter Gauge, no graph or graph in timeline
- [ ] Convert oGCDs as is.  Evaluate for future migration to core CDDT?
- [ ] Update Overheal to TypeScript, remove default export
- [ ] Update Swiftcast to TypeScript, remove default export

**Comment by psummers678** [comment]
Removed the default exports from overheal and swiftcast and swapped them both to TypeScript in the above pull request #1494
