### ISSUE TITLE
Monk Endwalker TODO

### ISSUE THREAD

**Issue by ayyaruq** [xivanalysis/xivanalysis#1303]
Tracking progress for MNK updates to make is easier for people to see when asking questions in Discord. If you feel like anything is incorrect or missing here, please feel free to leave a comment, or ping acchan#5683 in the #fb-monk channel on the xivanalysis Discord server. If you'd like to work on any of the remaining tasks, *please* reach out to the #dev-melee channel in Discord so we can make sure people aren't duplicating effort for things that are already in progress.

For the most part, this expansion simplifies the code quite a lot, we can remove a lot of edge case handling and only Twin is even a little complex going forward.

### Data Updates
- [x] Update Action entries in root layer #1471 
- [x] Update Status entries in root layer #1471 
- [x] Merge PGL actions into MNK #1321 

### Analyser Updates
- [x] Delete Fists analyser #1471 
- [ ] New Gauge analyser for Beast Chakras and Nadis (in progress - Ay)
- [x] New Masterful Blitz analyser #1492 
- [ ] Replace PB analyser - chart of gauge state, GCDs used, and Blitz used (in progress - Ay)
- [x] Simplify Twin Snakes analyser - we can gain from 4PF now #1471 
- [x] ~~Improve Demolish clipping tracking -  adjust the checklist dynamically, and trying to allow some clips~~ (no longer necessary)
- [x] Update RoF analyser to contain a Blitz #1492 
  - [x] Celestial Revolution is always a mistake #1650 
  - [ ] Add RoW to RoF windows?
  - [ ] Rising Phoenix in any RoF window that contains BH, otherwise Elixir Field, this is mostly to ensure Leaden Fist spam happens under both buffs but maybe shouldn't be enforced?
  - [x] Migrate to core BuffWindow to better handle BH and drift?
- [x] Add Riddle of Wind to CDDT #1471 
- [x] Add Riddle of Wind to a stats box #1645 

### Other Updates
- [x] Split out the Blitz BuffWindow evaluator so the code is easier to read #1615 
- [ ] Add a new BuffWindow evaluator for Drift and track BH in it (in progress - Square)

Gauge is going to be... spicy? I'm still thinking through code structure of what the Gauge analyser should be doing relative to PB and Blitz. We can use Gauge as a data backend where PB/Blitz manage calls to it for building or spending, or we could inline checks directly to it, or we could hook everything as needed in the Gauge and have Blitz/PB just offer suggestions however we currently can't hook on gauge state. Open to ideas.

**Comment by ayyaruq** [comment]
Brainstorming FoF a bit - what I'm thinking is to use core BuffWindow for the GCD counts, but then custom Evaluators for the actual columns so we can determine BH drift and window encapsulation, proper Blitz handling, and variable chakra display. Might be worth a notes column for which part of the rotation it's in and what we expect, such as BH being needed at all or which Blitzes.

The main reason FoF used a custom table instead of BuffWindow in Shadowbringers was that we had a lot of extra columns that the existing notes functionality didn't handle very well, but with the new Evaluator system I think this is no longer needed and tbh it's a pain to maintain.

**Comment by skimmedsquare** [comment]
Just putting stuff here in case people look here instead of the discord

 > Add a new BuffWindow evaluator for Drift and track BH in it
 
is currently in progress.
 
We probably need a to-do item for updating the blitz column in the RoF table to have expected counts instead of the 1/- or 2/- that currently displays

**Comment by ayyaruq** [comment]
The undefined expected count issue is a known problem affecting multiple jobs so I'd not worry too much about it, the actual issue is in the Rotation Table component. Updated the TODO to flag you as working on BH drift.

**Comment by hintxiv** [comment]
Stale, closing this for now (some of the items are completed, some are no longer relevant, some are still relevant and would be nice to have implemented)
