### ISSUE TITLE
Reaper Endwalker TODO

### ISSUE THREAD

**Issue by ayyaruq** [xivanalysis/xivanalysis#1372]
Tracking progress for RPR implementation to make is easier for people to see when asking questions in Discord. If you feel like anything is incorrect or missing here, please feel free to leave a comment, or ping acchan#5683 in the #fb-reaper channel on the xivanalysis Discord server.

### Data Implementation
- [x] Actions #1353 
- [x] Statuses #1353 

### Analyser Implementation
- [x] Soul Gauge #1623
- [x] Shroud Gauge #1623 
- [x] Death Gauge #1619 
- [x] AoE #1430 
- [x] CDDT #1430 
- [x] Combos #1430 
- [x] Interrupts #1430 
- [x] Weaving #1430 
- [x] Buff Uptime (Death's Design) #1427
- [x] Buff Window (Enshrouded, Arcane Circle) #1553
- [x] Enhanced procs for Gibbet/Gallows #1551
- [x] Plentiful Harvest prepull/downtime #1482
- [x] Immortal Sacrifice charges not being wasted #1482
- [x] Harvest Moon charging #1559 
- [x] Soulsow should be flagged if not used in downtime (this should be done *after* the cleanup PR is done)
- [x] Soul Reaver stacks wasted or misused #1625 
- [x] Filtered tincture windows #1429 

### Misc
- [x] cleanup junk code and flag support #1638

**Comment by hintxiv** [comment]
* Enshroud should be left out of CDDT since it's gauge-based
