### ISSUE TITLE
SGE Support TODO

### ISSUE THREAD

**Issue by AkairyuGestalter** [xivanalysis/xivanalysis#1421]
Non-exhausive list of things yet to do for Sage support:
- [x] Lost Addersgall to timer downtime suggestion
- [x] Lost Addersgall to Rhizomata cap suggestion
- [x] CDDT for Phlegma
- [x] Informational CDDT for non-Addersgall healing CDs (Including Pneuma, and probably Rhizomata)
- [x] Addersting overcap suggestion
- [x] Job description blurb
- [x] Job SVG/font stuff so it's not "e" anymore 🙃

**Comment by AkairyuGestalter** [comment]
Marking off the gauge suggestions since they're just waiting for #1434 to be approved/merged. Will do a final testing pass after that's in and fix any bugs while writing the blurb/marking as supported
