### ISSUE TITLE
SCH 6.0 update TODO

### ISSUE THREAD

**Issue by ghost** [xivanalysis/xivanalysis#1577]
- [x] Update Weaving module text (In Progress - Arkevorkhat) #1579 
- [x] Update Aetherflow Module (In Progress - dthomash) #1563 
- [x] Update Faerie Gauge (In Progress - Arkevorkhat) #1578 

Depends on all above:
- [x] Bump SCH to 6.08 (PR Up - Arkevorkhat) #1580

**Comment by ghost** [comment]
Tasks complete. Thanks everyone!~
