### ISSUE TITLE
Monk TODO

### ISSUE THREAD

**Issue by ayyaruq** [xivanalysis/xivanalysis#640]
Tracking progress for MNK updates to make is easier for people to see when asking questions in Discord mostly, since the TODO isn't always up to date. If you feel like anything is incorrect or missing here, please feel free to leave a comment, or ping `acchan#5683` in the xivanalysis Discord server.

### Gauge Uptime
- [x] Don't clip or drop Demolish by more than 2 seconds
- [x] Wasted RoE (no trigger Earth's Reply) #639
- [x] Fists, make sure at least one is up #445
- [x] Dragon Kick buff checking Boot #568
- [x] Twin Snakes uptime and clipping (adjust for the double True shenanigans) #612

### Forms
- [x] Reset forms by using Opo-Opo form skills in a different form #614
- [x] Form expiry (taking over 15s to transition) #614
- [x] Form Shifting under PB (WHY IS THIS A THING?) #583
- [x] Using formless Opo-Opo skills #614
- [x] Form Shifting mid-combo #614

### Positionals
FFLogs deletes this data, the best we can do is look for Boot crits:
- [x] Crit the Boot #568

### AoE
- [x] Make sure there's enough enemies for AotD, FPF, RB, and Enlightenment effectiveness #590, #615, #724

### Buff Windows
- [x] RoF rotation table #582, #723
- [ ] Brotherhood, include in RoF table maybe? #571, #582 
- [ ] BH vs RoF drift, ie BH starting or stopping outside RoF, questionable value tho
- [x] FBC counter in RoF+PB tables, purely visual
- [x] CDDT first use offsets
- [x] RoF action counts adjusted for 5.4
- [x] PB GCD counts adjusted for 5.4
- [x] 2x Shoulder Tackle (in window, vs ongoing on CD) #571, #582, #723
- [x] Form Shift and 6SS in PB is no bueno #583 (6SS currently not checked, limitations in core BuffWindow)

### 5.4 Specific Misc stuff
- [x] Update speedmod logic for trait
- [x] Delete GL gauge
- [x] Delete RoE module (maybe re-add later, if suggestions come up)
- [x] Form Shift new status
- [x] Potency data updates: GCDs, TK, 6SS
- [x] Potency modifier updates: GL effect on Fist/Action suggestion texts
- [x] Suggestion updates: TK, 6SS guidelines
- [ ] Twin dropping for ~2 GCDs in PB, update checklist target for this?
- [ ] PB table

**Comment by ayyaruq** [comment]
Updated TODO for changes in 5.4, removed some stuff that wasn't going anywhere even if it helps KR/CN since they'll have 5.4 within 4 months anyway.

**Comment by ayyaruq** [comment]
BH Drift and PB table definitely aren't going to happen pre-6.0 release. Twin is doable, however very complex to implement in code so I'm leaning towards leaving it as is for the Shadowbringers branch cutoff. With this, I'm closing the issue, however if anyone wants to tackle these (sorry not sorry), please reach out to me in Discord in either the #fb-monk, #dev-melee, or #dev-general channels.
