### ISSUE TITLE
Warrior TODO

### ISSUE THREAD

**Issue by ayyaruq** [xivanalysis/xivanalysis#860]
### Offensive Cooldown Usage
- [x] Upheaval with CooldownDowntime for drift and use checks (#907)
- [x] Infuriate tracking (Depends on having something for charge actions) (#907)
- [x] IR tracking: a lack of IRs should be obvious from its own module, but downtime could make things look weird when they're actually ok (CooldownDowntime here too?) (#907)
- [ ] Nascent Chaos timeouts
- [ ] Nascent Chaos overwriting

### Defensive Cooldowns
- [ ] People hit by Shake
- [ ] Raw vs Nascent maybe?

### Other
- [x] Clarify module titles a bit
- [x] AoE usages modules (#980)

**Comment by ayyaruq** [comment]
Closing as the pending work was largely not possible within data limitations, and with 6.0 no longer necessary.
