### ISSUE TITLE
Dragoon TODO

### ISSUE THREAD

**Issue by Rietty** [xivanalysis/xivanalysis#962]
Tracking progress for DRG updates to make is easier for people to see when asking questions in Discord mostly, shifting it out of the repository itself. If you feel like anything is incorrect or missing here, please feel free to leave a comment, or ping Julie#0001 in the XIVAnalysis Discord server.

Not Started:
- [ ] Fix the Ability Drift module where it breaks in rare-instances due to a possible null-check failing, particularly for Ultimate logs.

In-progress:
- [ ] Explore and possibly implement optimal DS usage/tether partners within new DS module. 
- [ ] Only using Jumps under BotD for that sweet damage buff.

Finished:
- [x] Separate out the logic for LC/DS into separate modules, and add them (along with BL) into a single output category of buffs.
- [x] Litany analysis added.
- [x] Enabling Tincture module & adding GSK to cooldowns section. 
- [x] Adjust first use offset for cooldowns to reflect new openers and remove old suggestion.
- [x] BotD uptime.
- [x] Not using Mirage Dive when at 2 eyes already.
- [x] Not entering LotD with less than 24s on BoTD.
- [x] 3 Nastronds per window.
- [x] Not missing/dropping Wheeling Thrust/Fang & Claw.
- [x] Not overwriting/dropping Mirage Dive procs.
- [x] Not double weaving with Jump actions.
- [x] Using Jumps on cooldown.
- [x] Only using Life Surge on Full Thrust/5th combo hit.
- [x] 8 GCDs under Blood for Blood.
- [x] 8 GCDs under Dragon Sight.
- [x] Using Blood for Blood at the right time in the rotation.
- [x] Piercing Resist Down uptime.
- [x] Chaos Thrust uptime and clipping.

Deprecated
- [x] Adhering to the standard 11-GCD rotation/rotation watchdog.
